CREATE TABLE IF NOT EXISTS teste (
	id SERIAL PRIMARY KEY
	, nome VARCHAR(50) NOT NULL
	, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS teste;

CREATE TABLE IF NOT EXISTS teste (
	cpf VARCHAR(11) NOT NULL
	, nome VARCHAR(50) NOT NULL
	, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	, PRIMARY KEY (cpf)
);

INSERT INTO teste (cpf, nome)
	VALUES ('12345678912','João Candido');
	
UPDATE teste SET nome = 'José Carlos' WHERE cpf = '12345678912';

SELECT * FROM teste;